### ISSUE TITLE
/stock/list endpoint missing

### ISSUE THREAD

**Issue by Devors** [DivanteLtd/vue-storefront-integration-boilerplate#17]
If `filterUnavailableVariants` set to `true` SF call to 
`rootStore.state.config.stock.endpoint + '/list?skus=' + encodeURIComponent(skus.join(',')`

**Comment by pkarw** [comment]
Thanks! Can You please add it to the docs as a PR? Thanks :)

**Comment by janmyszkier** [comment]
taking this over

**Comment by janmyszkier** [comment]
done in https://github.com/DivanteLtd/vue-storefront-integration-boilerplate/pull/19
closing
