### ISSUE TITLE
Add a sample PHP importer and API implementation

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront-integration-boilerplate#33]
We currently have the [importer](https://github.com/DivanteLtd/vue-storefront-integration-sdk/blob/tutorial/sample-data/import.js) and the [sample-api](https://github.com/DivanteLtd/vue-storefront-integration-sdk/tree/tutorial/sample-api-js) both implemented in the node-js. It would be awesome if someone would be willing to create PHP/Symfony based examples

**Comment by janmyszkier** [comment]
since this was moved over to another maintainer, I'm closing this as "won't fix" (at least not in this repo)
