### ISSUE TITLE
Integrate with django

### ISSUE THREAD

**Issue by j209** [DivanteLtd/vue-storefront-integration-boilerplate#36]
Hi
Can we integrate vuestorefront with django or any ecommerce framework that make with django like [Saleor](https://github.com/mirumee/saleor)?
And how we can compare vuestorefront to [pwa.saleor](https://github.com/mirumee/saleor-storefront)?

**Comment by janmyszkier** [comment]
@j209 Django itself is not a e-commerce framework. It's simply a Python Framework. There's no reason to connect vue-sf with django. 
Making Saleor (solution using django) integration could make sense, though and you're open to make it using this repository guide and then share with the community. Or hire someone through 
https://forum.vuestorefront.io/c/jobs

for starters the mirumee PWA is based on React, not on Vue, but if you look for functionality comparison, then you should head to https://www.vuestorefront.io/merchants/ and compare against saleor PWA.

the most important part is that mirumee connector is **not stable**, and for me that's the most important point to not use the Saleor connector at all until it is stable and production ready.
VueSF has been production ready for some time now.

**Comment by janmyszkier** [comment]
closing, because https://github.com/vuestorefront/saleor exists
