### ISSUE TITLE
Link to Configure vue-storefront broken

### ISSUE THREAD

**Issue by arproudlock** [DivanteLtd/vue-storefront-integration-boilerplate#42]
Link address should be https://github.com/DivanteLtd/storefront-integration-sdk/blob/tutorial/How%20to%20configure%20Vue%20Storefront.md

**Comment by janmyszkier** [comment]
@arproudlock from what I see was fixed by community PR: https://github.com/DivanteLtd/storefront-integration-sdk/pull/46/files. Feel free to let me know if this can be closed or I will close it eventually

**Comment by arproudlock** [comment]
Thank you.On 18 Aug 2020 21:44, Jan Myszkier <notifications@github.com> wrote:
@arproudlock from what I see was fixed by community PR: https://github.com/DivanteLtd/storefront-integration-sdk/pull/46/files. Feel free to let me know if this can be closed or I will close it eventually
